### ISSUE TITLE
New master after case page move not removed from the sock list

### ISSUE THREAD

**Issue by Dreamy-Jazz** [GeneralNotability/spihelper#11]
In https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/%D0%9E%D1%82%D1%80%D0%BE%D0%BA_12&diff=993517226&oldid=993517221 the sockmaster is not removed from the sock list after a case page move.

**Comment by Dreamy-Jazz** [comment]
Same with https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/Stjn&diff=994373429&oldid=994373421

**Comment by GeneralNotability** [comment]
I'm guessing it's that infernal `|master name` parameter. I'll look into this.

**Comment by GeneralNotability** [comment]
Should have been fixed in 2.2.15 (insufficiently escaped regex), reopen if it persists.
