### ISSUE TITLE
IPv6 addresses should be treated as case insensitive when generating block lists

### ISSUE THREAD

**Issue by Dreamy-Jazz** [GeneralNotability/spihelper#12]
For Wikipedia:Sockpuppet investigations/Hugo Refachinho ([diff to case](https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/Hugo_Refachinho&diff=995048586&oldid=995048478)), the two different capitalisations of IPv6 addresses in the second report (2001:8a0:6756:9b01:49b:ecdd:cd70:1933 and 2001:8A0:6756:9B01:49B:ECDD:CD70:1933) are treated as separate IP addresses in the block list. They should be treated as the same IP address, as IPv6 addresses are case insensitive. Therefore, only one should appear. I would prefer that IPv6 addresses are listed in capitals in the block list (as mediawiki automatically corrects lowercase to upper case when clicking on a link to a IPv6 address).

**Comment by GeneralNotability** [comment]
I'll bake this into a common username normalization function (also replacing underscores with spaces and things like that).

**Comment by GeneralNotability** [comment]
Fixed in 2.2.15 with a username normalization function.
