### ISSUE TITLE
Checkuser template not recognized when blocking/tagging accounts

### ISSUE THREAD

**Issue by roysmith** [GeneralNotability/spihelper#121]
https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/ASIANPOPCHANNEL&oldid=1098776017 had a {{checkuser}} template instead of a {{socklist}}.  Running spi-helper to block/tag didn't recognize the account.

Changing {{checkuser}} to {{socklist}} got things working again.

**Comment by GeneralNotability** [comment]
That's not a proper use of {{checkuser}}, so there's no fix to apply here; I do not think it is worth our time to work around people using templates incorrectly.
