### ISSUE TITLE
The log of actions after pressing "done" sometimes shows editing actions as failed with an error of http

### ISSUE THREAD

**Issue by Dreamy-Jazz** [GeneralNotability/spihelper#13]
This issue has no diff, but once I see it again I will take a screenshot if needed. On seemingly random occasions the script says that the addition of the log item failed even though it didn't. The error I see is just "http" next to the log item failed message. Not sure of cause, but might look further indepth later.

**Comment by Dreamy-Jazz** [comment]
Just had it happen again, put pressed refresh before I realized and could get a screenshot. It happened at Wikipedia:Sockpuppet investigations/Angela Criss and the http error also happened when requesting a global lock. That edit still went through though.

**Comment by GeneralNotability** [comment]
I've seen this happen on rare occasion, though I can't figure out what the "http" failure code means. I've added a bit of logging, next time this happens please open your browser's console and paste the error message if it's anything more detailed than "http".

**Comment by Dreamy-Jazz** [comment]
I haven't seen it since, so I suspect it is a issue with how SPI helper interprets responses from the API?

**Comment by GeneralNotability** [comment]
I have managed to get this to trigger by hitting refresh while spihelper is saving the log. Not sure what it means, mind you.

**Comment by Dreamy-Jazz** [comment]
I just got this error using a different script. I was using the AfC helper script and a comment I made failed with the error "http". This is likely a mediawiki issue.

**Comment by Dreamy-Jazz** [comment]
Not seen this error in ages. Plus refreshing the page when using the script has been made more difficult to achieve in normal use via a alert box after issue #19 was closed.
