### ISSUE TITLE
Block notification template when blocking IPs

### ISSUE THREAD

**Issue by Callanecc** [GeneralNotability/spihelper#17]
When I've used the script to block IPs (using "Block/tag socks") the script will block IPs but not leave a notification on the IP's talk page (with "Add talk page notice when blocking socks selected"). See, for example, [Wikipedia:Sockpuppet investigations/Specialwood](https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/Specialwood&oldid=997545293) and [Wikipedia:Sockpuppet investigations/Stevemalya](https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/Stevemalya&oldid=997544891). Could [Template:Uw-ipevadeblock](https://en.wikipedia.org/wiki/Template:Uw-ipevadeblock) please be used for this?

**Comment by GeneralNotability** [comment]
It should be leaving a talk page notice...let me look into this. I'm reluctant to use uw-ipevadeblock instead of uw-sockblock because the latter is more generic and the former doesn't cover things like "intentional logged-out editing to create false consensus," but I'll think about it.

**Comment by GeneralNotability** [comment]
Ahaa, found the issue. For whatever reason, the code that decided what type of message to leave on talk pages was checking the tag and _not_ adding a talk page notice if there wasn't a tag, and since we don't tag IPs...yeah. Queueing a fix in dev now.

**Comment by Callanecc** [comment]
Thanks. No issues with uw-sockblock.

**Comment by Callanecc** [comment]
Will the fix also deal with cases where accounts aren't tagged but are blocked. For example: https://en.wikipedia.org/wiki/Wikipedia:Sockpuppet_investigations/AveryGilmerrealestate?

**Comment by GeneralNotability** [comment]
Yup, it will fix that too.

**Comment by GeneralNotability** [comment]
Deployed this morning in 2.3.0.
