### ISSUE TITLE
More info case status

### ISSUE THREAD

**Issue by Callanecc** [GeneralNotability/spihelper#18]
Add support for moreinfo and cumoreinfo as separate case statuses being for different purposes. Ref: https://en.wikipedia.org/wiki/Template:SPI_case_status

The wording of moreinfo is about an admin or clerk needing more evidence (etc) to take _non-CU-related_ actions whereas cumoreinfo is for when a clerk or CU needs more evidence (etc) to take _CU-related actions_ (that is, carry out a CU or endorse a request for CU).

Based on this, moreinfo should appear for all current case statuses (it current doesn't for at least cudecline) whereas cumore info should only appear when the case status is curequest or endorse (and maybe open).

In the short term, could moreinfo be added as an option to all case statuses (it currently isn't for cudecline at least). 

Thanks.

**Comment by GeneralNotability** [comment]
Sure, that's an easy one. Will work on this.

**Comment by GeneralNotability** [comment]
In dev.

**Comment by Callanecc** [comment]
Thanks GN! Hopefully adding the cumoreinfo ("Request more info before CU" maybe) status will be fairly straight forward as well.

**Comment by GeneralNotability** [comment]
Deployed this morning in 2.3.0.
