### ISSUE TITLE
Warn about leaving the page when the script is running actions after pressing "Done"

### ISSUE THREAD

**Issue by Dreamy-Jazz** [GeneralNotability/spihelper#19]
Similarly to when the script warns about closing or leaving the page when in the second menu, ideally the script should also warn about leaving the page when there are actions/edits still to make. I sometimes am a bit hasty when clicking off after running the script, so ensuring that everything finishes before I click of is useful for me. Perhaps it might be worth also warning about leaving the page when an error has occurred too (so to ensure that the person running the script sees the error and corrects for it if needed). I would include when a user is not blocked as part of the definition of error, as its best to ensure that the person running the script sees any difference in what they wanted before leaving the page. If the going back is intentional then all it takes is to press "Leave page" or similar which doesn't take too long.

**Comment by GeneralNotability** [comment]
Not sure exactly how to implement it right now, but my general idea is that each call to one of the long-running functions would add an entry to a "dirty" list and remove that entry/set it to false/whatever when it finished, and if someone tries to leave the page the script intercepts the close and checks whether that list has any "dirty" entries.

**Comment by GeneralNotability** [comment]
Fixed in v2.5.0.
