### ISSUE TITLE
When using the select all checkbox for requesting global locks, IPs (which have the checkbox greyed out) are checked.

### ISSUE THREAD

**Issue by Dreamy-Jazz** [GeneralNotability/spihelper#26]
When requesting global locks on Wikipedia:Sockpuppet investigations/1234monkeystar, I used the select all checkbox for requesting global locks. The greyed out checkbox for the IP was selected, even though it couldn't be selected by itself.

**Comment by GeneralNotability** [comment]
This will be a pretty easy fix - looks like I actually tried to account for that but am incorrectly checking whether the _source_ (the select-all box) is disabled.

**Comment by GeneralNotability** [comment]
Released in 2.4.0.
