### ISSUE TITLE
Read master's block and lock settings and/or specify block settings on the case page

### ISSUE THREAD

**Issue by GeneralNotability** [GeneralNotability/spihelper#3]
Suggested by @dqwiki: some sockmasters should always have TPA revoked. I see two approaches to this: either automatically read the master's block settings (if blocked) and use those to autofill the block table, or specify those settings in the SPI somehow and read them.

**Comment by Dreamy-Jazz** [comment]
Probably best to specify somewhere in the SPI. TPA shouldn't be revoked ideally unless the sockmaster can be reasonably assumed to abuse it. Users who may be innocent need the chance to appeal, so I would say the tool should only automatically tick the TPA revoked box when it is currently needed. Perhaps a parameter in SPIarchive notice, like crosswiki, which adds "Socks should have TPA revoked". The tool can then read for this.

**Comment by Dreamy-Jazz** [comment]
@GeneralNotability this has been fixed by dbd7da7a540b160e3dcea8ed5766f3ae8fbbae92, so this issue should probably be closed.
