### ISSUE TITLE
Back to top menu link fails

### ISSUE THREAD

**Issue by Dreamy-Jazz** [GeneralNotability/spihelper#32]
When pressing "Back to top menu" it does not take you to the top menu anymore. The error in the console is:

Uncaught (in promise) TypeError: match is null
    spiHelper_parseArchiveNotice https://en.wikipedia.org/w/index.php?title=User:GeneralNotability/spihelper.js&action=raw&ctype=text/javascript:2715
    spiHelper_init https://en.wikipedia.org/w/index.php?title=User:GeneralNotability/spihelper.js&action=raw&ctype=text/javascript:266
    spiHelper_generateForm https://en.wikipedia.org/w/index.php?title=User:GeneralNotability/spihelper.js&action=raw&ctype=text/javascript:465
    jQuery 2
index.php:2715:19

There was also another error message in the console, but this one is probably unrelated. It is:
Malformed archivenotice parameter index.php:2722:13

The page was Wikipedia:Sockpuppet investigations/ArmanAfifeh.

**Comment by GeneralNotability** [comment]
Fixed in v2.5.1.
