### ISSUE TITLE
running the tool with limited functionality on archives manually

### ISSUE THREAD

**Issue by L235** [GeneralNotability/spihelper#47]
Fairly frequently, I find myself having to request locks on socks in an SPI archive, only to find that (by design) this tool doesn't load. Chastened, I request locks the old-fashioned way (i.e. bug a steward :-) ) rather than try to file an m:SRG request on my own. Is there some way to allow the script to load on /Archive pages, with limited functionality? Such as only with the block/tag/lock options?

This is a low-priority issue.

**Comment by Dreamy-Jazz** [comment]
I'd endorse having this.
