### ISSUE TITLE
Block message refers to User:null

### ISSUE THREAD

**Issue by roysmith** [GeneralNotability/spihelper#52]
See https://en.wikipedia.org/w/index.php?title=User_talk:GangstarDz&diff=1034438576&oldid=1034435270&diffmode=source

I blocked a sock, and the message that got left on their talk page said, "You have been blocked indefinitely from editing for abusing multiple accounts as a sockpuppet of User:null"

**Comment by L235** [comment]
I believe this happens when there's a popup with the question "Who is the sockmaster" or something like that, and the user doesn't answer.

**Comment by roysmith** [comment]
I'm pretty sure I got the popup and hit return to accept the default like I usually do.

**Comment by TheresNoTime** [comment]
Noting another instance of this [here](https://meta.wikimedia.org/w/index.php?title=Steward_requests/Global&diff=prev&oldid=21802318) - this was indeed caused by me clicking off of the `prompt`.

Have a fix inbound 😸
