### ISSUE TITLE
Sanity check user config

### ISSUE THREAD

**Issue by GeneralNotability** [GeneralNotability/spihelper#62]
Check for unexpected values in user options and fall back on sane defaults - see #35.

**Comment by Dreamy-Jazz** [comment]
One issue here is that spihelper.js basically needs access to a JavaScript implementation of php's strtotime, unless the API is used. Javascript's inbuilt option does not detect anywhere close to what PHP detects, so a custom function will likely be needed to validate before sending to strtotime. An example library that emulates strtotime in php is https://github.com/locutusjs/locutus/blob/master/src/php/datetime/strtotime.js which is over 1000 lines long of JS code.

Trying to use the API doesn't seem to work either. I cannot find a way to validate the expiry option using the API without actually trying to watch the page and seeing if the expiry worked.

**Comment by Dreamy-Jazz** [comment]
Found a way to achieve validating a date. Using parser functions and then parsing the wikitext will achieve what is needed here. I will write a patch.
