### ISSUE TITLE
What to do if TPA / Email is already revoked on a block which is being overriden

### ISSUE THREAD

**Issue by Dreamy-Jazz** [GeneralNotability/spihelper#72]
For example, in Wikipedia:Sockpuppet investigations/Afroditeiraq I CU blocked an account which already had it's TPA removed. However the override of the block re-enabled talk page access. Options:

1. Read whether TPA / Email is already disabled on a block, and pre-check the tickboxes in the SPI block form. This means that the user has the option to re-enable TPA or Email, but only does so when they explicitly uncheck a box.
2. Don't change the TPA / Email setting if it's already set to disabled, regardless of whether override blocks is set
3. This is the intended behavior, and if TPA / Email should be revoked the person who overrided the block should have to check the box to continue to have TPA / Email removed.

Ideally I would say 1 is the preferred option. This is because socks can be non-CU blocked who then abuse TPA, but then once a CU block is applied TPA still needs to be removed as they are likely to continue to abuse it. If TPA needs to be re-enabled, then the admin overriding the block can just uncheck remove TPA.

**Comment by GeneralNotability** [comment]
option 1 is the behavior we want, I think, and I laid the groundwork toward implementation in a past release (added a helper function to get block status), just haven't actually implemented this part.

**Comment by Dreamy-Jazz** [comment]
Fixed by e983106.
