### ISSUE TITLE
Don't tag accounts that don't exist.

### ISSUE THREAD

**Issue by roysmith** [GeneralNotability/spihelper#73]
See https://en.wikipedia.org/wiki/Wikipedia:Sockpuppet_investigations/Pswank91

I left the default "block everybody" configuration, even though two accounts (User:Louis XIV of France and User:Ludwig I of Bavaria) didn't exist on enwiki.  It noticed this when blocking, but went ahead and tagged the non-accounts anyway.

**Comment by Dreamy-Jazz** [comment]
I'd prefer to confirm if tags are wanted, and if it's a yes tag the user without specifying the account is blocked locally. This could probably be achieved by setting notblocked to yes. I'll make a patch to develop for this.
